### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by altrazmedia** [Nitrooos/nitrooos.github.io#24]
"We can’t connect to the server at nitrooos.pl."

**Comment by Nitrooos** [comment]
Thank you for reporting @altrazmedia ! We're currently working hard on making that address available again, temporarily you can access the blog under: nitrooos.github.io

**Comment by Nitrooos** [comment]
@altrazmedia The issue was resolved, now you can normally access blog under https://nitrooos.pl
